sudo apt install -y \
    bat \
    build-essential \
    curl \
    cmake \
    fd-find \
    git \
    htop \
    httpie \
    locales \
    libbz2-dev \
    libffi-dev \
    liblzma-dev \
    libreadline-dev \
    libsqlite3-dev \
    libssl-dev \
    libz-dev \
    nginx \
    ripgrep \
    silversearcher-ag \
    software-properties-common \
    sudo \
    tmux \
    tree \
    unzip \
    uuid-runtime \
    vim \
    zlib1g-dev \
    tk-dev \
    zsh \
