export GOPATH="$HOME/Go"
BITCOIN_PATH="$HOME/bitcoin/bin"
PATH="/usr/local/bin:$PATH"
PATH="$HOME/commands:$PATH"
PATH="$BITCOIN_PATH:$PATH"
PATH="$GOPATH/bin:$PATH"
export PATH="/Users/jikkujose/miniconda2/bin:$PATH"
