COMPLETION_WAITING_DOTS="true"
DISABLE_AUTO_TITLE="true"
DISABLE_AUTO_UPDATE="true"
DISABLE_UNTRACKED_FILES_DIRTY="true"
DISPLAY=:0
HISTFILESIZE=120000
HISTSIZE=120000
HISTTIMEFORMAT='%b %d %H:%M:%S > '
KEYTIMEOUT=1
RUBYOPT=""

OLLAMA_HOST="0.0.0.0"
OLLAMA_BASE_URL="http://localhost:11434"
DISPLAY=:1
