COMPLETION_WAITING_DOTS="true"
DISABLE_AUTO_TITLE="true"
DISABLE_AUTO_UPDATE="true"
DISABLE_UNTRACKED_FILES_DIRTY="true"
DISPLAY=:0
# Disable history
HISTSIZE=0
SAVEHIST=0
unset HISTFILE
KEYTIMEOUT=1
RUBYOPT=""

OLLAMA_HOST="0.0.0.0"
OLLAMA_BASE_URL="http://localhost:11434"
DISPLAY=:1
